ARG VERSION=latest
ARG APK_ADD=""
ARG APK_TEMP_ADD=""
ARG DOCKER_PHP_EXT_INSTALL=""
ARG PECL_INSTALL=""
ARG DOCKER_PHP_EXT_ENABLE=""

FROM localhost/fs/php/php:${VERSION}

USER root

RUN apk add --no-cache ${APK_ADD} ${APK_TEMP_ADD} ${PHPIZE_DEPS}
RUN docker-php-ext-install ${DOCKER_PHP_EXT_INSTALL}
RUN pecl install ${PECL_INSTALL}
RUN docker-php-ext-enable ${DOCKER_PHP_EXT_ENABLE}
RUN apk del ${APK_TEMP_ADD} ${PHPIZE_DEPS}

WORKDIR /app

USER php
