ARG FROM_TAG=latest

FROM fedora:${FROM_TAG}

RUN dnf install -y samba

COPY smb.conf /etc/samba/smb.conf
COPY users.list /tmp

RUN while IFS=":" read -r user pass; do \
    useradd $user; \
    printf "$pass\n$pass\n" | smbpasswd -a $user; \
    done < /tmp/users.list

RUN rm -f /tmp/users.list

RUN mkdir -p /data/share
WORKDIR /data/share

CMD /bin/bash -c "smbd --foreground --log-stdout --no-process-group"
