ARG FROM_TAG=latest
ARG APK_ADD=""
ARG APK_TEMP_ADD=""
ARG DOCKER_PHP_EXT_INSTALL=""
ARG PECL_INSTALL=""
ARG DOCKER_PHP_EXT_ENABLE=""

FROM localhost/fs/php/xdebug:${FROM_TAG}

USER root
ENV XDEBUG_MODE coverage

RUN apk add --no-cache ${PHPIZE_DEPS} git zip coreutils
RUN [ -z ${DOCKER_PHP_EXT_INSTALL} ] || docker-php-ext-install ${DOCKER_PHP_EXT_INSTALL}
RUN [ -z ${PECL_INSTALL} ] || pecl install ${PECL_INSTALL}
RUN [ -z ${DOCKER_PHP_EXT_ENABLE} ] || docker-php-ext-enable ${DOCKER_PHP_EXT_ENABLE}
RUN apk del ${APK_TEMP_ADD} ${PHPIZE_DEPS}

USER php

WORKDIR /tmp
RUN curl https://getcomposer.org/installer > composer-setup.php
RUN curl https://composer.github.io/installer.sha384sum > installer.sha384sum
RUN sha384sum -c installer.sha384sum
RUN php composer-setup.php
RUN rm -f composer-setup.php

USER root
RUN mv composer.phar /usr/local/bin/composer
RUN apk del coreutils

WORKDIR /app
USER php
