ARG VERSION=latest
FROM php:${VERSION}-cli-alpine

RUN apk add --no-cache git zip libzip-dev pcre-dev ${PHPIZE_DEPS}
RUN docker-php-ext-install zip
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
RUN apk del pcre-dev ${PHPIZE_DEPS}

RUN echo "phar.readonly = Off" >> /usr/local/etc/php/php.ini

RUN apk add --no-cache coreutils
RUN addgroup --gid 1000 php && adduser -u 1000 -G php -s /bin/bash -D php
USER php

WORKDIR /tmp
RUN curl https://getcomposer.org/installer > composer-setup.php
RUN curl https://composer.github.io/installer.sha384sum > installer.sha384sum
RUN sha384sum -c installer.sha384sum
RUN php composer-setup.php
RUN rm -f composer-setup.php

USER root
RUN mv composer.phar /usr/local/bin/composer
RUN apk del coreutils

RUN mkdir /app
WORKDIR /app

USER php
